# Generated by Django 5.2.3 on 2025-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="PrimaryKey", primary_key=True, serialize=False
                    ),
                ),
                (
                    "dba_name_billing_name",
                    models.CharField(
                        db_column='"DBA Name Billing Name"', max_length=255
                    ),
                ),
                (
                    "address_full",
                    models.CharField(db_column='"Address 1 Full"', max_length=255),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True, db_column='"Billing Name"', max_length=255
                    ),
                ),
                ("tin", models.CharField(blank=True, db_column='"TIN"', max_length=50)),
                ("npi", models.CharField(blank=True, db_column='"NPI"', max_length=50)),
                (
                    "provider_type",
                    models.CharField(
                        blank=True, db_column='"Provider Type"', max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, db_column='"Latitude"', null=True),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, db_column='"Longitude"', null=True),
                ),
            ],
            options={
                "db_table": "providers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email_id",
                    models.CharField(
                        help_text="Unique identifier for the email",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        blank=True,
                        help_text="Outlook conversation ID for thread linking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line of the email",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "email_from",
                    models.CharField(
                        blank=True,
                        help_text="Sender email address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_received_datetime",
                    models.CharField(
                        blank=True,
                        help_text="When the email was received",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "referral",
                    models.BooleanField(
                        blank=True, help_text="Whether this is a referral", null=True
                    ),
                ),
                (
                    "employer_address",
                    models.TextField(
                        blank=True, help_text="Employer's address", null=True
                    ),
                ),
                (
                    "employer_email",
                    models.CharField(
                        blank=True,
                        help_text="Employer's email address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "injury_description",
                    models.TextField(
                        blank=True, help_text="Description of the injury", null=True
                    ),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True, help_text="Diagnosis code", max_length=50, null=True
                    ),
                ),
                (
                    "icd_code",
                    models.CharField(
                        blank=True,
                        help_text="ICD-10 diagnosis code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "diagnosis_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed diagnosis description",
                        null=True,
                    ),
                ),
                (
                    "intake_client_company",
                    models.CharField(
                        blank=True,
                        help_text="Client company name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "intake_client_email",
                    models.CharField(
                        blank=True,
                        help_text="Client email address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "intake_client_name",
                    models.CharField(
                        blank=True,
                        help_text="Client contact name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "intake_client_phone",
                    models.CharField(
                        blank=True,
                        help_text="Client phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "intake_adjuster_name",
                    models.CharField(
                        blank=True, help_text="Adjuster name", max_length=255, null=True
                    ),
                ),
                (
                    "intake_adjuster_email",
                    models.CharField(
                        blank=True,
                        help_text="Adjuster email address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "intake_adjuster_phone",
                    models.CharField(
                        blank=True,
                        help_text="Adjuster phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        blank=True,
                        help_text="Patient's full name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "patient_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        help_text="Patient's gender",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True,
                        help_text="Patient identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "patient_dob",
                    models.CharField(
                        blank=True,
                        help_text="Patient's date of birth",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "patient_doi",
                    models.CharField(
                        blank=True,
                        help_text="Patient's date of injury",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "patient_address",
                    models.TextField(
                        blank=True, help_text="Patient's address", null=True
                    ),
                ),
                (
                    "patient_email",
                    models.CharField(
                        blank=True,
                        help_text="Patient's email address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "patient_phone",
                    models.CharField(
                        blank=True,
                        help_text="Patient's phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        help_text="Order/reference number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "intake_preferred_provider",
                    models.CharField(
                        blank=True,
                        help_text="Preferred provider for intake",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "intake_requested_procedure",
                    models.TextField(
                        blank=True,
                        help_text="Requested medical procedure(s)",
                        null=True,
                    ),
                ),
                (
                    "intake_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for intake",
                        null=True,
                    ),
                ),
                (
                    "patient_instructions",
                    models.TextField(
                        blank=True, help_text="Instructions for the patient", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Urgent", "Urgent"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                            ("Routine", "Routine"),
                        ],
                        help_text="Priority level of the referral",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "referring_provider_name",
                    models.CharField(
                        blank=True,
                        help_text="Referring provider's name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "referring_provider_npi",
                    models.CharField(
                        blank=True,
                        help_text="Referring provider's NPI number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "referring_provider_address",
                    models.TextField(
                        blank=True, help_text="Referring provider's address", null=True
                    ),
                ),
                (
                    "referring_provider_email",
                    models.CharField(
                        blank=True,
                        help_text="Referring provider's email",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "referring_provider_phone",
                    models.CharField(
                        blank=True,
                        help_text="Referring provider's phone",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "processed_attachments",
                    models.TextField(
                        blank=True,
                        help_text="JSON array of processed attachments",
                        null=True,
                    ),
                ),
                (
                    "assigned_provider",
                    models.CharField(
                        blank=True,
                        help_text="PrimaryKey of the assigned provider",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="Latitude coordinate", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="Longitude coordinate", null=True
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, help_text="When geocoding was performed", null=True
                    ),
                ),
                (
                    "geocoding_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of geocoding process",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "raw_s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 key for raw file",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "extracted_json",
                    models.CharField(
                        blank=True,
                        help_text="Path to extracted JSON file",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "corrected_json",
                    models.CharField(
                        blank=True,
                        help_text="Path to corrected JSON file",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this referral has been processed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "db_table": "referrals",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
